name: CI

on:
  push:
    branches:
    - main
    - release/*
  schedule:
  - cron: "0 2 * * 1-5"
  
jobs:
  gnu:
    name: Process the GNU test results
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        path: repo/

    - name: Download the result
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: GNU.yml
        name: gnu-result
        repo: uutils/coreutils
        path: repo/

    - name: Add & Commit
      uses: EndBug/add-and-commit@v7.2.1
      with:
        cwd: ./repo/
        default_author: github_actions
        message: "Update of the GNU data"
        add: gnu-result.json

    - name: Setup deno
      uses: denolib/setup-deno@v2
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Fetch data
      uses: githubocto/flat@v2
      with:
        http_url: https://raw.githubusercontent.com/sylvestre/coreutils-tracking/main/gnu-result.json
        downloaded_filename: dat
