name: CI

on:
  push:
    branches:
    - main
    - release/*
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  gnu:
    name: Process the GNU test results
    runs-on: ubuntu-latest
    steps:
    - name: Install deps
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install jq python3-pandas python3-matplotlib

    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        path: repo/

    - name: Download the result
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: GNU.yml
        name: gnu-result
        repo: uutils/coreutils

    - name: Merge the json files
      shell: bash
      run: |
       jq -s '.[0] * .[1]' gnu-result.json repo/gnu-result.json > merged.json
       cat merged.json
       mv merged.json repo/gnu-result.json

    - name: Add & Commit
      uses: EndBug/add-and-commit@v7.2.1
      with:
        cwd: ./repo/
        default_author: github_actions
        message: "Update of the GNU data"
        add: gnu-result.json

    - name: Generate the graph
      shell: bash
      run: |
        python repo/graph.py
        cp -f gnu-results.png repo/

    - name: Add & Commit the graph
      uses: EndBug/add-and-commit@v7.2.1
      with:
        cwd: ./repo/
        default_author: github_actions
        message: "Refresh the graph"
        add: gnu-results.png
